#!/usr/bin/env bash
# =============================================================================
# aks-up.sh — Provision the dev/test AKS cluster + ACR via Terraform,
#             configure kubectl, and render a local Helm values file.
# =============================================================================
# Steps:
#   1. Pre-flight checks (terraform, az, kubectl, helm, az login)
#   2. terraform init && terraform apply (in infra/aks/)
#   3. az aks get-credentials  (overwrites local kubeconfig entry)
#   4. Render chart/values-aks.local.yaml with live OIDC issuer + ACR
#   5. Print next-step instructions
#
# Idempotent: re-running re-applies state and re-renders the local values file.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$REPO_ROOT/infra/aks"
CHART_DIR="$REPO_ROOT/chart"
VALUES_TEMPLATE="$CHART_DIR/values-aks.yaml"
VALUES_LOCAL="$CHART_DIR/values-aks.local.yaml"

CYAN='\033[0;36m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

header() { printf "\n${CYAN}=== %s ===${NC}\n" "$1"; }
info()   { printf "  ${YELLOW}%s${NC}\n" "$1"; }
ok()     { printf "  ${GREEN}[OK]${NC} %s\n" "$1"; }
fail()   { printf "  ${RED}[ERROR]${NC} %s\n" "$1"; exit 1; }
step()   { printf "\n${YELLOW}▶ %s${NC}\n" "$1"; }

header "DevSecOps Demo — AKS Bootstrap"

# -----------------------------------------------------------------------------
# Step 1: Pre-flight
# -----------------------------------------------------------------------------
header "Pre-flight checks"

for bin in terraform az kubectl helm; do
  if command -v "$bin" >/dev/null 2>&1; then
    ok "$bin found: $(command -v "$bin")"
  else
    fail "$bin not found on PATH. See infra/aks/README.md."
  fi
done

if ! az account show >/dev/null 2>&1; then
  fail "Not signed in to Azure. Run: az login"
fi
SUB_NAME=$(az account show --query name -o tsv 2>/dev/null || echo "<unknown>")
SUB_ID=$(az account show --query id -o tsv 2>/dev/null || echo "<unknown>")
ok "Azure subscription: $SUB_NAME ($SUB_ID)"

[ -d "$INFRA_DIR" ] || fail "Terraform stack not found at $INFRA_DIR"

# -----------------------------------------------------------------------------
# Step 2: terraform init && apply
# -----------------------------------------------------------------------------
header "Provisioning AKS + ACR via Terraform"

step "terraform init"
terraform -chdir="$INFRA_DIR" init -input=false

step "terraform apply"
TF_APPLY_ARGS=(-input=false)
if [ "${AUTO_APPROVE:-false}" = "true" ]; then
  TF_APPLY_ARGS+=(-auto-approve)
fi
terraform -chdir="$INFRA_DIR" apply "${TF_APPLY_ARGS[@]}"

# -----------------------------------------------------------------------------
# Step 3: Retrieve outputs + kubeconfig
# -----------------------------------------------------------------------------
header "Reading Terraform outputs"

tf_out() { terraform -chdir="$INFRA_DIR" output -raw "$1"; }

RG=$(tf_out resource_group_name)
CLUSTER=$(tf_out cluster_name)
ACR_NAME=$(tf_out acr_name)
ACR_LOGIN_SERVER=$(tf_out acr_login_server)
OIDC_URL=$(tf_out oidc_issuer_url)
LOCATION=$(tf_out location)

ok "Resource group:    $RG"
ok "AKS cluster:       $CLUSTER ($LOCATION)"
ok "ACR:               $ACR_NAME  ($ACR_LOGIN_SERVER)"
ok "OIDC issuer URL:   $OIDC_URL"

[ -n "$OIDC_URL" ] || fail "OIDC issuer URL is empty — Fulcio keyless signing will not work. Check AVM module version."

step "az aks get-credentials"
az aks get-credentials -g "$RG" -n "$CLUSTER" --overwrite-existing --only-show-errors
ok "kubeconfig updated"

# -----------------------------------------------------------------------------
# Step 4: Render local Helm values file
# -----------------------------------------------------------------------------
header "Rendering $VALUES_LOCAL"

[ -f "$VALUES_TEMPLATE" ] || fail "Template missing: $VALUES_TEMPLATE"

# Use python for safe templating — sed of URLs containing slashes is error-prone.
python3 - "$VALUES_TEMPLATE" "$VALUES_LOCAL" "$ACR_LOGIN_SERVER" "$OIDC_URL" <<'PY'
import sys, pathlib
src, dst, acr, oidc = sys.argv[1:5]
text = pathlib.Path(src).read_text()
text = text.replace("<YOUR_ACR_NAME>.azurecr.io", acr)
text = text.replace("<OIDC_ISSUER_URL>", oidc)
header = (
    "# AUTO-GENERATED by scripts/aks-up.sh — do not edit.\n"
    "# Source template: chart/values-aks.yaml\n"
    f"# Rendered for ACR={acr} OIDC={oidc}\n"
)
pathlib.Path(dst).write_text(header + text)
PY
ok "Wrote $VALUES_LOCAL"

# -----------------------------------------------------------------------------
# Step 5: Next steps
# -----------------------------------------------------------------------------
header "Next steps"
cat <<EOF

  Cluster is ready. To install the demo stack:

    VALUES_FILE=$VALUES_LOCAL bash scripts/install.sh

  To build and push demo images to ACR:

    bash scripts/build-and-push.sh

  To tear everything down:

    bash scripts/aks-down.sh

EOF
